/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelReservationProgram_V2;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.StreamCorruptedException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdussamet
 */
public class DosyaOkuma extends javax.swing.JFrame {

    /**
     * Creates new form DosyaOkuma
     */
    ArrayList<Path> dosyalar = new ArrayList();
    DefaultComboBoxModel dcm = new DefaultComboBoxModel();

    public DosyaOkuma() {
        initComponents();
    }

    public DosyaOkuma(ArrayList<Path> dosyalar) {
        initComponents();
        this.dosyalar = dosyalar;

        for (Path p : dosyalar) {
            dcm.addElement(p);
        }

        jComboBoxDosyalar.setModel(dcm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxDosyalar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonDonustur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dosyalarınız:");

        jComboBoxDosyalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDosyalarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonDonustur.setText("Dönüştür");
        jButtonDonustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDonusturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBoxDosyalar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButtonDonustur)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDosyalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDonustur))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDosyalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDosyalarActionPerformed
        jTextArea1.setText("");
        BufferedReader br = null;
        String file = "C:\\Users\\Abdussamet\\Documents\\NetBeansProjects\\Abdussamet_KACI_1721221007_BP2_Odev2\\src\\abdussamet_kacı_1721221007_bp2_odev2\\" + jComboBoxDosyalar.getSelectedItem();
        try {
            br = new BufferedReader(new FileReader(file));
            String yazi;
            while ((yazi = br.readLine()) != null) {
                if (!yazi.equals("")) {
                    jTextArea1.append(yazi + "\n");
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxDosyalarActionPerformed

    private void jButtonDonusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDonusturActionPerformed
        jTextArea1.setText("");
        
        ObjectInputStream ois = null;
        String file = "C:\\Users\\Abdussamet\\Documents\\NetBeansProjects\\Abdussamet_KACI_1721221007_BP2_Odev2\\src\\abdussamet_kacı_1721221007_bp2_odev2\\" + jComboBoxDosyalar.getSelectedItem();
        try {
            ois = new ObjectInputStream(new BufferedInputStream(new FileInputStream(file)));

            while (true) {
                Musteri m = (Musteri) ois.readObject();
                String yazi = "" + m.getAd() + ", " + m.getSoyad() + ", " + m.getTc() + ", " + m.getEmail() + ", " + m.getCinsiyet() + ", " + m.getTel() + ", " + m.getYas() + ", " + m.getKullaniciadi() + ", " + m.getSifre() + ", " + m.getOtel() + ", " + m.getOda() + ", " + m.getAldigihizmetler() + ", " + m.getFatura() + "\n";
                jTextArea1.append(yazi);
            }
            
        } catch (EOFException ex) {
            
            
        } catch (FileNotFoundException ex) {

        } catch (StreamCorruptedException ex) {
            datDosyasiniOku(file);

        } catch (IOException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                ois.close();
            } catch (IOException ex) {
                Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex) {
                
            }
        }
    }//GEN-LAST:event_jButtonDonusturActionPerformed

    private void datDosyasiniOku(String file) {
        jTextArea1.setText("");
        DataInputStream dis = null;
        try {
            dis = new DataInputStream(new BufferedInputStream(new FileInputStream(file)));
            while (dis.available() > 0) {
                jTextArea1.append(dis.readUTF());
            }
        } catch (EOFException ex) {
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                dis.close();
            } catch (IOException ex) {
                Logger.getLogger(DosyaOkuma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosyaOkuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosyaOkuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosyaOkuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosyaOkuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosyaOkuma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDonustur;
    private javax.swing.JComboBox<String> jComboBoxDosyalar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
